
name: cctalk

services:
  nacos:
    image: nacos/nacos-server:v2.2.0
    environment:
      MODE: "standalone"
    ports:
      - '8848:8848'
      - '9848:9848'
    expose:
      - '8848'
      - '9848'
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mydata/mysql/log:/var/log/mysql
      - ./mydata/mysql/data:/var/lib/mysql
      - ./mydata/mysql/my.cnf:/etc/my.cnf
  cache:
    image: redis:latest
    command: redis-server /etc/redis/redis.conf
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '6379:6379'
    expose:
      # Opens port 3306 on the container
      - '6379'
      # Where our data will be persisted
    volumes:
      - ./mydata/redis/data:/data
      - ./mydata/redis/redis.conf:/etc/redis/redis.conf



